### ISSUE TITLE
TypeError: '<' not supported between instances of 'float' and 'NoneType'

### ISSUE THREAD

**Issue by Tylersuard** [drewlinsley/pathfinder#2]
when running snakes.py:

  (np.float(raw_num_available_coordinates)/(mask.shape[0]*mask.shape[1]) < stop_with_availability):
Traceback (most recent call last):
  File "snakes.py", line 643, in <module>
    test()
  File "snakes.py", line 499, in test
    allow_incomplete=False, allow_shorter_snakes=False)
  File "snakes.py", line 66, in make_many_snakes
    aa_scale, display_snake, display_segment, allow_shorter_snakes, stop_with_availability)
  File "snakes.py", line 124, in make_snake
    aa_scale= aa_scale, display=display_segment, stop_with_availability=stop_with_availability)
  File "snakes.py", line 191, in seed_snake
    (np.float(raw_num_available_coordinates)/(mask.shape[0]*mask.shape[1]) < stop_with_availability):
TypeError: '<' not supported between instances of 'float' and 'NoneType'

**Comment by drewlinsley** [comment]
Sorry for the delayed response. I believe these issues are because this codebase was written in Python 2. I will try to find time to convert. 

Note that Google did that for their long range arena: https://github.com/google-research/long-range-arena In case you need the code soon.

**Comment by Tylersuard** [comment]
That is helpful, thank you.  I wasn't able to find code in long-range-arena that generates pathfinder images, only code that downloads them.

**Comment by drewlinsley** [comment]
I believe this should work https://github.com/google-research/long-range-arena/blob/main/lra_benchmarks/data/pathfinder.py

**Comment by Tylersuard** [comment]
Thank you Drew.  I was able to get your code up and running in Python 2.
I've seen Pathfinder in many sequence modelling papers and it's really important to the field.  You might already know this, but Facebook recently released MEGA, which scored a 97% on the Pathfinder-X dataset.  I wanted to generate an even more challenging Pathfinder-X2 dataset, with image sizes of 512x512 and 1024x1024.  I'm not sure if I am doing it right though.  
![1sample_964](https://user-images.githubusercontent.com/41713505/229311593-8024276b-6061-4b77-b148-320db9d64e02.png)

**Comment by drewlinsley** [comment]
Thanks!

Yes this looks great. If you really want to kill those models try to follow what we did in this paper ;-) (fig 2) https://arxiv.org/abs/2005.11362

**Comment by Tylersuard** [comment]
Ok!  I read the paper, and I used your suggestion of long snakes and a segmentation task.  I generated 200k images for the inputs and 200k images for the label.  I wrote a short paper on it where I cited you, would you like to be listed as a co-author?  https://www.overleaf.com/read/rpsmdnxbdfjt

**Comment by drewlinsley** [comment]
I appreciate the offer! The citation is more than enough though. Paper looks great. Congrats!
